[connections.snowflake]
account = "JGRFGEE-MCB05008"
user = "SjoerdGeels"
password = "Sj03rdTry1ng#Sn0wfl4k3"
role = "SYSADMIN"
warehouse = "COMPUT_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_Session_keep_alive = true
